### ISSUE TITLE
Building instructions

### ISSUE THREAD

**Issue by DFL1973** [MiSTeX-devel/Main_MiSTeX#3]
I believe the building instructions are from an older version: "Makefile.arm64" now, I suppose, but I have some missing libs that I didn't figure out how to install in Ubuntu. (-lfreetype, -lbz2, -lpng16, -lz, -lImlib2, -lgpiod, -lbluetooth all for "armhf" I guess?).

Anyway, is the "Makefile.arm64" the correct one for the RPi zero? Or "Makefile.riscv"? 

Thanks for sharing

**Comment by DFL1973** [comment]
Or please add a pre-built RPI zero binary under /releases
thanks!

**Comment by hansfbaier** [comment]
Ah, Makefile is now the Makefile for the Pi Zero.
arm64 is for bigger machines, and is currently unmaintained

**Comment by hansfbaier** [comment]
OK I made a release, included the binary and the SDK in case you want to build yourself and updated the README with the build instructions
https://github.com/MiSTeX-devel/Main_MiSTeX/releases/tag/0.0.1

**Comment by DFL1973** [comment]
Thanks, I really appreciate that. Even with the new instructions, I'm still getting missing Scrt1.o and crtbwginS.o but should be my Ubuntu.
Anyway, I hope you can help me a little more. I get your Mister binary and looks like it´s working. After I built the Menu core for a QMtech Altera, I can navigate the folders and options with a USB keyboard attached in RPI zero. So, I built the Qbert arcade, but I can´t figure out how to put them on the SD card. 

After some reading, I put qbert.zip (roms, not extracted) into the pre-existent _Arcade/mame them QBERT_XXXXX.rbf into _Arcade/cores. After the boot, the Menu can't find any core, so I moved the RBF to /_Arcade with the MRAs files. I can see the now, but if I select the core I get a quick window with "error uploading /media/fat/_Arc" (cropped message). Attaching a monitor to the RPI I can't see any relevant message.

So, I'm "almost there", but, please can you provide a little more info on how to use the core? maybe an usbblaster attached to jtag?

**Comment by hansfbaier** [comment]
You have to change the bitstream extension from .bit to .rbf in MiSTer.ini

**Comment by hansfbaier** [comment]
For flashing I currently use an rp2040 with the dirtyJtag firmware connected to the USB of the RPi

**Comment by DFL1973** [comment]
> You have to change the bitstream extension from .bit to .rbf in MiSTer.ini

I don´t have any option like that in my .ini. (using the original SD card image from buildroot)

EDIT: I just found a mister.ini on the main_mistex folder. That one has the "bitstream_extension=". 
changed to .rbf, but still the same error

EDIT2: just added "fpgaloader_cmd=" on .ini. Im using a usbblaster and I pre-tested the command line at RPI zero prompt. The transfer works under the prompt, but the Menu still has the same issue. I believe the menu can't find the .RBF file in /media/fat/_Arcade. Where is the right place to drop the RBF file?

**Comment by hansfbaier** [comment]
Sorry, I was on my phone, when I ansered this (PC was off).
The config option is: `bitstream_extension=.bit`
Or in your case rather: The config option is: `bitstream_extension=.rbf`
I also updated the Distribution_MiSTeX submodule in the buildroot accordingly.

**Comment by hansfbaier** [comment]
@DFL1973 The rbf file needs to be in /media/fat/_Arcade/cores

**Comment by hansfbaier** [comment]
@DFL1973 The rbf file needs to be in /media/fat/_Arcade/cores

**Comment by hansfbaier** [comment]
BTW, you don't need to use Menu to load a core, you can just use openFPGAloader directly, and then manually start /media/fat/MiSTer That is often helpful for development.

**Comment by DFL1973** [comment]
> BTW, you don't need to use Menu to load a core, you can just use openFPGAloader directly, and then manually start /media/fat/MiSTer That is often helpful for development.

Yes, but the idea is to try the full cycle, boot, select a core, then load. For development, I will do a direct load for sure.



> @DFL1973 The rbf file needs to be in /media/fat/_Arcade/cores

still nothing. now doesn't even show on the list. Selecting the MRA by hand I got the same error.

**Comment by hansfbaier** [comment]
What does the MiSTer output look like when loading the Arcade dir?

**Comment by hansfbaier** [comment]
We can make a video call with screen sharing, if you like.
